export const ordinalNumberings = {
  1: "Primeira",
  2: "Segunda",
  3: "Terceira",
  4: "Quarta",
  5: "Quinta",
  6: "Sexta",
  7: "Sétima",
  8: "Oitava",
  9: "Nona",
  10: "Décima",
  11: "Décima e primeira",
  12: "Décima e segunda",
  13: "Décima e terceira",
  14: "Décima e quarta",
  15: "Décima e quinta",
  16: "Décima e sexta",
  17: "Décima e sétima",
  18: "Décima e oitava",
  19: "Décima e nova",
  20: "Vigésima",
  21: "Vigésima e primeira",
  22: "Vigésima e segunda",
  23: "Vigésima e terceira",
  24: "Vigésima e quarta",
  25: "Vigésima e quinta",
  26: "Vigésima e sexta",
  27: "Vigésima e sétima",
  28: "Vigésima e oitava",
  29: "Vigésima e nova",
};
